# Generated by Django 3.1.6 on 2021-03-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
                ('like', models.ManyToManyField(related_name='liked', to='ExamApp.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='ExamApp.user')),
            ],
        ),
    ]
